name: Binaries Release

on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
    # https://github.com/actions/checkout#checkout-multiple-repos-nested
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout binaries
      uses: actions/checkout@v2
      with:
        repository: x186k/deadsfu-binaries
        path: deadsfu-binaries
        ref: main
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        ldflags: -X main.Version=${{ github.event.release.tag_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
 #      goversion: "https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz"
        goversion: "1.16.5"
        project_path: "."
        binary_name: "deadsfu"
        asset_name: deadsfu-${{ matrix.goos }}-${{ matrix.goarch }}
# default is ${BINARY_NAME}-${RELEASE_TAG}-${GOOS}-${GOARCH}
# but my version allows direct downloads using:
# https://github.com/x186k/deadsfu/releases/latest/download/deadsfu-linux-amd64.tar.gz
# https://github.com/x186k/deadsfu/releases/latest/download/deadsfu-darwin-amd64.tar.gz
# https://github.com/x186k/deadsfu/releases/latest/download/deadsfu-darwin-arm64.tar.gz
# https://github.com/x186k/deadsfu/releases/latest/download/deadsfu-windows-amd64.tar.gz
# etc
