name: Docker Release

on:
  release:
    types: [created]

jobs:
  docker-build-push:
#    if: false
    name: docker build and push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# aparently docker-compose pull is faster than a cache
      # - run: docker-compose pull
      - name: Checkout binaries repo
        uses: actions/checkout@v2
        with:
          repository: x186k/deadsfu-binaries
          path: deadsfu-binaries
          ref: main
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: x186k/deadsfu # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
# I am really tempted to cut this crap down, but github doesn't seem to mind building
# i guess arm/v6 arm/v7 can help with raspberry pi's
# i am not sure who the linux/386 is for, but let's leave it incase.
#           platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
#           platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
