
name: website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      # run:
      #   working-directory: websi
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" 
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: 'sfu1'

      - uses: actions/checkout@v2
        with:
          repository: 'cameronelliott/mkdocs-bulma'
          path: 'mkdocs-bulma'
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
          
#  - name: Cache dependencies
#    uses: actions/cache@v1
#    with:
#      path: ~/.cache/pip
#      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#      restore-keys: |
#        ${{ runner.os }}-pip-
    
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
#          python3 -m pip install mkdocs-material

      - name: Build site
        run: mkdocs build
          working-directory: sfu1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sfu1/site