# This is a basic workflow to help you get started with Actions
# https://gist.github.com/wilsontwm/28beb84b0bad67d03c8c2bff18a75188


name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    name: Run the linter
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35.2
        args: --skip-files pion.go

    # - name: Install dependencies
    #   run: |
    #     go version
    #     go get
        
    # Run build of the application
    # - name: Run build
    #   run: go build . 
    
    # - name: Deploy to Docker registry
    #   uses: docker/build-push-action@v1
    #   with:
    #     #target: janus-factory
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: x186k/sfu-x186k
    #     tag_with_ref: true
    #     tag_with_sha: true

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64 
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'  

    - name: Run build
      run: go build . 

#upload to releases
