name: deadsfu

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub so makefile push will work
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make release VER=${{ github.event.release.tag_name }}
